add_newline = false

format = """$directory$character"""
# right_format = """$all"""

[directory]
truncation_length = 2

[git_branch]
disabled = false
ignore_branches = ["master", "main", "develop"]
symbol = 'ðŸŒ¿ '

[git_status]
disabled = true

[package]
disabled = true

[dotnet]
disabled = true

[nodejs]
disabled = true
